### ISSUE TITLE
SwingActiveRender on JWindow?

### ISSUE THREAD

**Issue by AlissonSteffens** [dorkbox/Notify#12]
I'm trying to use a custom Notify version on my project. Using TweenEngine (8.3) and Notify-Dorkbox-Util (2.18)

On Notify @dorkbox  uses the removeActiveRender with notifyCanvas (for hideAfter feature):
```
SwingActiveRender.removeActiveRender(notifyCanvas);
```

but I can't use it, it says I can only use a JFrame as param.

Am I using some wrong version of lib or what?

Can some one help me?

**Comment by dorkbox** [comment]
I'm in the middle of changing everything over to the gradle build system, and so I can't push a release/bug fix for you.  The main problem is that you are using the Utils library (which is deprecated now), and won't work at all with more recent versions of the Notfiy project (it was deprecated over a major version release ago)

I just pushed some changes to the Swing ActiveRender system that accept a component (instead of a canvas), which should solve your problem. I recommend downloading my Utilities project (there is a gradle.build file for that project - so it should pull in all the extra imports you'll need), then copying over the files you need.

Once I have everything converted to gradle, it will be a ton easier - until then it will be a huge pain... :(

**Comment by AlissonSteffens** [comment]
Yay, tnks for the fast answer :smile: 
I'll try to do it :+1:

**Comment by AlissonSteffens** [comment]
I used the new [ActiverRenderLoop](https://git.dorkbox.com/dorkbox/Utilities/src/commit/f9915fafcbfd12874ef85b07dbae8169c223d79e/src/dorkbox/util/swing/ActiveRenderLoop.java) and [SwingActiveRender](https://git.dorkbox.com/dorkbox/Utilities/src/commit/f9915fafcbfd12874ef85b07dbae8169c223d79e/src/dorkbox/util/swing/SwingActiveRender.java) now it's working :+1: 

tanks @dorkbox
