### ISSUE TITLE
NoClassDefFoundError for dorkbox/util/swing/ActiveRenderLoop (v2.14)

### ISSUE THREAD

**Issue by denuno** [dorkbox/Notify#2]
I'm getting this when trying to use Notify:

```
Caused by: java.lang.NoClassDefFoundError: dorkbox/util/swing/ActiveRenderLoop
        at dorkbox.util.swing.SwingActiveRender.<clinit>(SwingActiveRender.java:34)
```
I don't see that class anywhere, any idea why it's happening?

**Comment by bdw429s** [comment]
Any ideas @dorkbox ?  We'd like to use notify, but ActiveRenderLoop appears to be a ghost class.  Also, is there a hosted repo for `Notify-Dorkbox-Util`?  I've only been able to see the sources from the source downloads on Maven.

**Comment by dorkbox** [comment]
I'll work on this today -- I've been swamped with other project, but this should seem like an easy enough thing to fix

**Comment by dorkbox** [comment]
OK, see release `2.15`, it now has the missing file. Apologies for missing that file!  

@bdw429s, to answer your question about the Util repo, it's not hosted because there is a decent amount of proprietary code in it, and licensing is always an issue. It's difficult to license the entire Util package as Apache 2.0, and significantly easier if there's a need for 'split' projects. Just for a bit of trivia, almost all of the projects in the github repo were part of 'Utils' at one point.

**Comment by denuno** [comment]
Now I'm getting a noClassDef for SynchronizedEventQueue, can you add that one too, @dorkbox?

**Comment by dorkbox** [comment]
Absolutely. I'll add that in the morning.

**Comment by dorkbox** [comment]
Ok, it's updated. I also added the other files in that package (to completely "disable" the Swing EDT, for example). I also updated the readme + other documentation to "more properly" describe what this is and how to do it (if you want to do so outside of the scope of the Notify project)
